program tests

  ! Driver program for FRUIT unit tests in:
  ! linalg_test.f90
  ! assignment_test.f90
  ! l2m_test.f90

  ! Generated by FRUITPy.

  use fruit
  use linalg_test
  use assignment_test
  use l2m_test

  implicit none
  integer :: failed_count

  call init_fruit

  ! linalg_test.f90:
  call run_test_case(test_linalg_wrapper,"test_linalg_wrapper")

  ! assignment_test.f90:
  call run_test_case(test_assignment_square,"test_assignment_square")
  call run_test_case(test_assignment_rectangular_more_rows,"test_assignment_rectangular_more_rows")
  call run_test_case(test_assignment_rectangular_more_cols,"test_assignment_rectangular_more_cols")

  ! l2m_test.f90:
  call run_test_case(test_l2m_getlvl2minors,"test_l2m_getlvl2minors")

  call get_failed_count(failed_count)
  call fruit_summary
  call fruit_finalize
  if (failed_count > 0) stop 1

end program tests